create table kingdom
(
    id           integer generated by default as identity
        primary key,
    kingdom_name varchar(255),
    description  varchar(255)
);

alter table kingdom
    owner to postgres;

create table coin
(
    id         bigint generated by default as identity
        primary key,
    name       varchar(255),
    kingdom_id integer
        constraint uk8upii9nckejl4uygn8ydw0cja
            unique
        constraint fkd2tmx5loh3d4wh6vacx8tew41
            references kingdom,
    symbol     varchar(255)
);

alter table coin
    owner to postgres;

create table product
(
    id         bigint generated by default as identity
        primary key,
    base_price numeric(38, 2),
    name       varchar(255)
);

alter table product
    owner to postgres;

create table exchange_tax
(
    id         bigint generated by default as identity
        primary key,
    tax        numeric(38, 2),
    tax_date   date,
    destiny_id bigint
        constraint fkhdvyxiqlpuoe4f1xql0lx6hfw
            references coin,
    origin_id  bigint
        constraint fk1y76jcs2gc01gy9cfxlskgma2
            references coin,
    product_id bigint
        constraint fki41i3rup4mvo6iry7hm9aaa5c
            references product
);

alter table exchange_tax
    owner to postgres;

create table transaction
(
    id                    bigint generated by default as identity
        primary key,
    amount_destiny        numeric(38, 2),
    amount_origin         numeric(38, 2),
    transaction_date_time timestamp(6),
    destiny_coin_id       bigint
        constraint fkcbiyetpxl21offm8bb1u2olt3
            references coin,
    exchange_tax_id       bigint
        constraint fkpv8gqbya8yhx9yc1ijdtk6lht
            references exchange_tax,
    kingdom_id            integer
        constraint fkbhjhvbjmhl2jqiy13v54b1yqd
            references kingdom,
    origin_coin_id        bigint
        constraint fkt29su6lhf2don87jl1i6db21l
            references coin,
    product_id            bigint
        constraint fk1bkeyn2xhcnk7jnxpj1xvjd5m
            references product
);

alter table transaction
    owner to postgres;

